name: Codebase Index Validation

on:
  push:
    branches: [ main, 'release/*' ]
    paths:
      - 'scripts/gen-codebase-index.ts'
      - 'docs/codebase-index.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/gen-codebase-index.ts'
      - 'docs/codebase-index.json'

jobs:
  validate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install
      
      # The generate step is no longer needed as validate internally reuses the generation logic
      # - name: Generate codebase index
      #   run: |
      #     # This step has been removed as the validate step below internally generates the index
          
      - name: Validate codebase index
        run: |
          # Run validation in check mode
          # This will internally generate the index and compare it with the committed version
          pnpm codebase-index --check || {
            echo "❌ Index validation failed"
            echo "This indicates the index is out of date or there's an issue with the index generation logic"
            exit 1
          }
          
          echo "The Validate Codebase index check was successful"
